In [1]:
X = [3, 6, 1, 9, 2, 4, 7]

In [30]:
dic = { "MG": {"Capital": "Belo Horizonte", 
               "Cidades": {1:"Contagem", 
                           2:"Luiz de Fora", 
                           3:"Sete Lagoas"}
              },
        "SP": {"Capital": "São Paulo", 
               "Cidades": {1:"Campinas", 
                           2:"Piracicaba",
                           3:"Franca"}
              },
        "RS": {"Capital": "Porto Alegre", 
               "Cidades": {1:"Pelotas", 
                           2:"Gramado", 
                           3:"Canela"}
              } 
      }
print(dic["MG"]["Cidades"][2])

Luiz de Fora


In [28]:
dic["MG"]["Cidades"][2] = "Juiz de Fora"

In [29]:
dic

{'MG': {'Capital': 'Belo Horizonte',
  'Cidades': {1: 'Contagem', 2: 'Juiz de Fora', 3: 'Sete Lagoas'}},
 'SP': {'Capital': 'São Paulo',
  'Cidades': {1: 'Campinas', 2: 'Piracicaba', 3: 'Franca'}},
 'RS': {'Capital': 'Porto Alegre',
  'Cidades': {1: 'Pelotas', 2: 'Gramado', 3: 'Canela'}}}

In [31]:
estrutura_aninhada = ( [1,2,3],(4,5,6,7),[8,9],( [10,11,12], [(13, 14), 15] ) )

In [43]:
n = '5'

In [48]:
x = range(7)
soma = sum(filter(lambda x_i: x_i % 2 == 0, x))
print(soma)

12


In [69]:
import numpy as np
A = np.arange(1, 16).reshape(3,5)

In [70]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [79]:
A[1]

array([ 6,  7,  8,  9, 10])

In [72]:
A[-3]

array([1, 2, 3, 4, 5])

In [87]:

linha1 = A[1,0:]
linha1

array([ 6,  7,  8,  9, 10])